# Generated by Django 5.2.18 on 2026-10-07 03:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='課程名稱')),
            ],
            options={
                'verbose_name': '課程',
                'verbose_name_plural': '課程',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_label', models.CharField(max_length=50, verbose_name='章節標籤')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('audio', models.FileField(blank=True, upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(['mp3'])], verbose_name='音訊 MP3')),
                ('cover', models.ImageField(blank=True, upload_to='covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='書封')),
                ('content', models.TextField(blank=True, help_text='僅限受信任的管理員輸入 HTML。', verbose_name='內容簡介（HTML）')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.course', verbose_name='課程')),
            ],
            options={
                'verbose_name': '章節',
                'verbose_name_plural': '章節',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='已完成')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lecture', verbose_name='章節')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '閱讀進度',
                'verbose_name_plural': '閱讀進度',
                'unique_together': {('user', 'lecture')},
            },
        ),
    ]
