# Generated by Django 5.2.18 on 2026-10-07 06:33

import courses.models
import courses.storage
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='公開銷售介紹'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(blank=True, help_text='留空不開放結帳；一次付款，購買權限無到期日。', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20000000)], verbose_name='整套售價（新臺幣元）'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='audio',
            field=models.FileField(blank=True, storage=courses.storage.private_audio_storage, upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(['mp3'])], verbose_name='音訊 MP3'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_trade_no', models.CharField(default=courses.models.merchant_trade_number, editable=False, max_length=20, unique=True, verbose_name='商店訂單編號')),
                ('course_title', models.CharField(max_length=200, verbose_name='購買時課程名稱')),
                ('amount', models.PositiveIntegerField(verbose_name='訂單金額（新臺幣元）')),
                ('merchant_id', models.CharField(max_length=20, verbose_name='綠界商店代號')),
                ('is_test', models.BooleanField(default=True, verbose_name='測試環境')),
                ('status', models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('failed', '付款失敗')], default='pending', max_length=10, verbose_name='付款狀態')),
                ('gateway_trade_no', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='綠界交易編號')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='付款時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course', verbose_name='課程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_mac', models.CharField(max_length=64, unique=True, verbose_name='通知識別碼')),
                ('trade_no', models.CharField(max_length=20, verbose_name='綠界交易編號')),
                ('amount', models.PositiveIntegerField(verbose_name='付款金額')),
                ('rtn_code', models.IntegerField(verbose_name='付款結果代碼')),
                ('simulated', models.BooleanField(verbose_name='模擬付款')),
                ('payment_type', models.CharField(max_length=30, verbose_name='付款方式')),
                ('applied', models.BooleanField(default=False, verbose_name='已開通課程')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='接收時間')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='courses.order', verbose_name='訂單')),
            ],
            options={
                'verbose_name': '已驗簽付款通知',
                'verbose_name_plural': '已驗簽付款通知',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='有效購買權限')),
                ('is_test', models.BooleanField(default=False, verbose_name='僅限測試環境的權限')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後異動')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='課程')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.order', verbose_name='來源訂單')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '購買權限',
                'verbose_name_plural': '購買權限',
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='unique_course_purchase')],
            },
        ),
    ]
